import { Issue, Comment, IssueCategory, IssueStatus, IssuePriority } from './types';

export const mockIssues: Issue[] = [
  {
    id: '1',
    title: 'Large pothole on Main Street causing accidents',
    description: 'There is a dangerous pothole approximately 2 feet wide near the intersection of Main Street and Oak Avenue. Multiple vehicles have been damaged and it poses a serious risk to motorcyclists and cyclists.',
    category: 'pothole',
    status: 'in-progress',
    priority: 'high',
    location: {
      address: '123 Main Street, Downtown',
      lat: 40.7128,
      lng: -74.006,
    },
    images: ['/placeholder.svg'],
    reportedBy: {
      id: 'u1',
      name: 'Sarah Johnson',
      avatar: undefined,
    },
    reportedAt: new Date('2024-01-15T10:30:00'),
    updatedAt: new Date('2024-01-17T14:20:00'),
    upvotes: 47,
    hasUpvoted: false,
    commentsCount: 12,
    assignedDepartment: 'Public Works',
  },
  {
    id: '2',
    title: 'Overflowing garbage bins at Central Park',
    description: 'The garbage bins near the Central Park playground have been overflowing for 3 days. The smell is unbearable and it\'s attracting pests. This is a health hazard for children playing in the area.',
    category: 'garbage',
    status: 'acknowledged',
    priority: 'medium',
    location: {
      address: 'Central Park, Playground Area',
      lat: 40.7829,
      lng: -73.9654,
    },
    images: ['/placeholder.svg'],
    reportedBy: {
      id: 'u2',
      name: 'Michael Chen',
      avatar: undefined,
    },
    reportedAt: new Date('2024-01-16T08:15:00'),
    updatedAt: new Date('2024-01-16T16:45:00'),
    upvotes: 32,
    hasUpvoted: true,
    commentsCount: 8,
    assignedDepartment: 'Sanitation',
  },
  {
    id: '3',
    title: 'Water main leak flooding residential area',
    description: 'Major water leak from underground pipe. Water is flooding the street and entering nearby basements. Urgent attention required to prevent property damage.',
    category: 'water',
    status: 'reported',
    priority: 'critical',
    location: {
      address: '456 Elm Street, Riverside District',
      lat: 40.7589,
      lng: -73.9851,
    },
    images: ['/placeholder.svg'],
    reportedBy: {
      id: 'u3',
      name: 'Emily Rodriguez',
      avatar: undefined,
    },
    reportedAt: new Date('2024-01-17T07:00:00'),
    updatedAt: new Date('2024-01-17T07:00:00'),
    upvotes: 89,
    hasUpvoted: false,
    commentsCount: 23,
  },
  {
    id: '4',
    title: 'Multiple streetlights out on Harbor Drive',
    description: 'A stretch of about 10 streetlights are not working on Harbor Drive between 5th and 8th Avenue. The area is completely dark at night, making it unsafe for pedestrians.',
    category: 'streetlight',
    status: 'resolved',
    priority: 'medium',
    location: {
      address: 'Harbor Drive, between 5th and 8th Ave',
      lat: 40.7484,
      lng: -73.9967,
    },
    images: ['/placeholder.svg'],
    reportedBy: {
      id: 'u4',
      name: 'David Kim',
      avatar: undefined,
    },
    reportedAt: new Date('2024-01-10T19:30:00'),
    updatedAt: new Date('2024-01-16T11:00:00'),
    upvotes: 28,
    hasUpvoted: false,
    commentsCount: 6,
    assignedDepartment: 'Electrical Services',
    resolvedAt: new Date('2024-01-16T11:00:00'),
  },
  {
    id: '5',
    title: 'Broken traffic signal at busy intersection',
    description: 'The traffic light at the intersection of Broadway and 42nd Street is malfunctioning. It\'s stuck on red in all directions, causing massive traffic jams during rush hours.',
    category: 'traffic',
    status: 'in-progress',
    priority: 'high',
    location: {
      address: 'Broadway & 42nd Street',
      lat: 40.7559,
      lng: -73.9866,
    },
    images: ['/placeholder.svg'],
    reportedBy: {
      id: 'u5',
      name: 'Lisa Thompson',
      avatar: undefined,
    },
    reportedAt: new Date('2024-01-17T08:45:00'),
    updatedAt: new Date('2024-01-17T10:30:00'),
    upvotes: 156,
    hasUpvoted: false,
    commentsCount: 34,
    assignedDepartment: 'Traffic Management',
  },
  {
    id: '6',
    title: 'Unsafe playground equipment',
    description: 'The swing set at Riverside Park has broken chains and rusty bolts. A child almost got injured yesterday. The equipment needs immediate inspection and repair.',
    category: 'safety',
    status: 'acknowledged',
    priority: 'critical',
    location: {
      address: 'Riverside Park, Children\'s Area',
      lat: 40.8015,
      lng: -73.9683,
    },
    images: ['/placeholder.svg'],
    reportedBy: {
      id: 'u6',
      name: 'Amanda Foster',
      avatar: undefined,
    },
    reportedAt: new Date('2024-01-16T15:20:00'),
    updatedAt: new Date('2024-01-17T09:00:00'),
    upvotes: 72,
    hasUpvoted: true,
    commentsCount: 15,
    assignedDepartment: 'Parks & Recreation',
  },
];

export const mockComments: Comment[] = [
  {
    id: 'c1',
    issueId: '1',
    author: {
      id: 'u7',
      name: 'James Wilson',
    },
    content: 'I hit this pothole yesterday and damaged my tire. This needs to be fixed ASAP!',
    createdAt: new Date('2024-01-15T14:30:00'),
  },
  {
    id: 'c2',
    issueId: '1',
    author: {
      id: 'official1',
      name: 'Public Works Department',
      isOfficial: true,
    },
    content: 'Thank you for reporting this issue. Our team has been dispatched and repairs are scheduled for tomorrow morning.',
    createdAt: new Date('2024-01-16T09:15:00'),
  },
  {
    id: 'c3',
    issueId: '1',
    author: {
      id: 'u8',
      name: 'Patricia Brown',
    },
    content: 'I\'ve seen city workers marking the area today. Looks like they\'re preparing for repairs.',
    createdAt: new Date('2024-01-17T11:45:00'),
  },
];

export const dashboardStats = {
  totalIssues: 1247,
  resolvedThisMonth: 342,
  averageResolutionTime: '4.2 days',
  citizenSatisfaction: 87,
  issuesByCategory: {
    pothole: 312,
    garbage: 289,
    water: 156,
    streetlight: 198,
    traffic: 167,
    safety: 125,
  },
  issuesByStatus: {
    reported: 234,
    acknowledged: 187,
    'in-progress': 312,
    resolved: 514,
  },
  trendsData: [
    { month: 'Aug', reported: 145, resolved: 132 },
    { month: 'Sep', reported: 178, resolved: 156 },
    { month: 'Oct', reported: 192, resolved: 184 },
    { month: 'Nov', reported: 167, resolved: 175 },
    { month: 'Dec', reported: 203, resolved: 189 },
    { month: 'Jan', reported: 234, resolved: 215 },
  ],
};
